sudo: required
services:
  - docker

before_install:
  - docker build -t 333456/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 333456/react-test npm test

after_success:
  - docker build -t 333456/multi-client ./client
  - docker build -t 333456/multi-server ./server
  - docker build -t 333456/multi-worker ./worker
  - docker build -t 333456/multi-nginx ./nginx
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 333456/multi-client
  - docker push 333456/multi-server
  - docker push 333456/multi-worker
  - docker push 333456/multi-nginx
